version: '3.7'

services:
  backend:
    restart: unless-stopped
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    working_dir: /usr/src/app
    command: sh -c "yarn install && yarn prisma:generate && yarn start:migrate:dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    ports:
      - '7999:3000'
      - '9229:9229'
    links:
      - database
    depends_on:
      - database

  database:
    container_name: database
    restart: unless-stopped
    image: postgres:14.5
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgres/data

volumes:
  database-data:

networks:
  default:
    name: nest
